travis:
  secure:
    BINSTAR_TOKEN: YUxk5IKCAkJaqchyeDFnb+cnaMC8DbbRSJMRiv1VajsAg7f0Qe3nbwisJ7+ZtSBE0Mgz4RY7M3c2HU5NSXK4mVjltsiSWzYd4mwG9sqbHlxMrYy0MM03b7yNsMltVIiywSqKh4Rn6sju0NATlM3/XO1kI3NgRE3k8qC79xzNlM1/WiXpVRyM6C2hx8wm0eF4eWoGffcknoV9MRiW3CZZa4FZDt8ZTKk2E4AffW4UOo7WzyiykInDHMlejQNT+kGxvs7GNB6aRyEUa5R/R1yLocP6eT/bGpQRZWAI6n02SaTzik6+xMkvYiWQZxjF5ulRwxB0jTHCF1GXUViiRwxuYKMMyaVPQ7kV7p/qGeckAaU8BA78nq1LZ+tZ0iGw3B0TaD3nXvj3Xpa54HnjezEDTDIJGdWQHORkMagAAWtH2qR9Q4yVaH79BpCT1B8C11aWPAh3cTOOuH1uN0bDv7ludX0jQWJqPhFltNqfFcoAy7hWqSKa+Jaoj6efUgu2+07DFKFVc0Dda7JQQbY87ityYD024/xpYOuaFAIfcYSDRU3oackjmTCQHt2uIzLdKv9tWXSXGK3W7mE9Gnqqr0BZ7flE5Pur2ty5rqkFU1o8OsagwgY3u6zv28jx+AiblH0XvSx3QR6TttLiUpbbcATHRw+E/mBswHYhgQAhUL39lAg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
